const city = {
    arhangelsk: {
      name: "Архангельск",
      genitive: "Архангельска",
      dative: "Архангельску",
      accusative: "Архангельск",
      instrumental: "Архангельском",
      prepositional: "Архангельске",
      phone_display: "8(800)000-00-01",
      phone_href: "88000000001",
      address: "ул. Архангельская, д. 21",
      email: "arhangelsk.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    astrahan: {
      name: "Астрахань",
      genitive: "Астрахани",
      dative: "Астрахани",
      accusative: "Астрахань",
      instrumental: "Астраханью",
      prepositional: "Астрахани",
      phone_display: "8(800)000-00-02",
      phone_href: "88000000002",
      address: "ул. Астраханская, д. 21",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999",
      email: "astrahan.metall@mail.ru"
    },
    belgorod: {
      name: "Белгород",
      genitive: "Белгорода",
      dative: "Белгороду",
      accusative: "Белгород",
      instrumental: "Белгородом",
      prepositional: "Белгороде",
      phone_display: "8(800)000-00-03",
      phone_href: "88000000003",
      address: "ул. Белгородская, д. 21",
      email: "belgorod.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    bryansk: {
      name: "Брянск",
      genitive: "Брянска",
      dative: "Брянску",
      accusative: "Брянск",
      instrumental: "Брянском",
      prepositional: "Брянске",
      phone_display: "8(800)000-00-04",
      phone_href: "88000000004",
      address: "ул. Брянская, д. 21",
      email: "bryansk.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    vladivostok: {
      name: "Владивосток",
      genitive: "Владивостока",
      dative: "Владивостоку",
      accusative: "Владивосток",
      instrumental: "Владивостоком",
      prepositional: "Владивостоке",
      phone_display: "8(800)000-00-05",
      phone_href: "88000000005",
      address: "ул. Владивостокская, д. 21",
      email: "vladivostok.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    vladimir: {
      name: "Владимир",
      genitive: "Владимира",
      dative: "Владимиру",
      accusative: "Владимир",
      instrumental: "Владимиром",
      prepositional: "Владимире",
      phone_display: "8(800)000-00-06",
      phone_href: "88000000006",
      address: "ул. Владимирская, д. 21",
      email: "vladimir.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    volgograd: {
      name: "Волгоград",
      genitive: "Волгограда",
      dative: "Волгограду",
      accusative: "Волгоград",
      instrumental: "Волгоградом",
      prepositional: "Волгограде",
      phone_display: "8(800)000-00-07",
      phone_href: "88000000007",
      address: "ул. Волгоградская, д. 21",
      email: "volgograd.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    voronezh: {
      name: "Воронеж",
      genitive: "Воронежа",
      dative: "Воронежу",
      accusative: "Воронеж",
      instrumental: "Воронежем",
      prepositional: "Воронеже",
      phone_display: "8(800)000-00-08",
      phone_href: "88000000008",
      address: "ул. Воронежская, д. 21",
      email: "voronezh.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    dzerzhinsk: {
      name: "Дзержинск",
      genitive: "Дзержинска",
      dative: "Дзержинску",
      accusative: "Дзержинск",
      instrumental: "Дзержинском",
      prepositional: "Дзержинске",
      phone_display: "8(800)000-00-09",
      phone_href: "88000000009",
      address: "ул. Дзержинская, д. 21",
      email: "dzerzhinsk.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    donetsk: {
      name: "Донецк",
      genitive: "Донецка",
      dative: "Донецку",
      accusative: "Донецк",
      instrumental: "Донецком",
      prepositional: "Донецке",
      phone_display: "8(800)000-00-10",
      phone_href: "88000000010",
      address: "ул. Донецкая, д. 21",
      email: "donetsk.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    ekaterinburg: {
      name: "Екатеринбург",
      genitive: "Екатеринбурга",
      dative: "Екатеринбургу",
      accusative: "Екатеринбург",
      instrumental: "Екатеринбургом",
      prepositional: "Екатеринбурге",
      phone_display: "8(800)000-00-11",
      phone_href: "88000000011",
      address: "ул. Екатеринбургская, д. 21",
      email: "ekaterinburg.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    irkutsk: {
      name: "Иркутск",
      genitive: "Иркутска",
      dative: "Иркутску",
      accusative: "Иркутск",
      instrumental: "Иркутском",
      prepositional: "Иркутске",
      phone_display: "8(800)000-00-12",
      phone_href: "88000000012",
      address: "ул. Иркутская, д. 21",
      email: "irkutsk.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    kazan: {
      name: "Казань",
      genitive: "Казани",
      dative: "Казани",
      accusative: "Казань",
      instrumental: "Казанью",
      prepositional: "Казани",
      phone_display: "8(800)000-00-13",
      phone_href: "88000000013",
      address: "ул. Казанская, д. 21",
      email: "kazan.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    kaluga: {
      name: "Калуга",
      genitive: "Калуги",
      dative: "Калуге",
      accusative: "Калугу",
      instrumental: "Калугой",
      prepositional: "Калуге",
      phone_display: "8(800)000-00-14",
      phone_href: "88000000014",
      address: "ул. Калужская, д. 21",
      email: "kaluga.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    kemerovo: {
      name: "Кемерово",
      genitive: "Кемерово",
      dative: "Кемерово",
      accusative: "Кемерово",
      instrumental: "Кемерово",
      prepositional: "Кемерово",
      phone_display: "8(800)000-00-15",
      phone_href: "88000000015",
      address: "ул. Кемеровская, д. 21",
      email: "kemerovo.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    krasnodar: {
      name: "Краснодар",
      genitive: "Краснодара",
      dative: "Краснодару",
      accusative: "Краснодар",
      instrumental: "Краснодаром",
      prepositional: "Краснодаре",
      phone_display: "8(800)000-00-16",
      phone_href: "88000000016",
      address: "ул. Краснодарская, д. 21",
      email: "krasnodar.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    krasnoyarsk: {
      name: "Красноярск",
      genitive: "Красноярска",
      dative: "Красноярску",
      accusative: "Красноярск",
      instrumental: "Красноярском",
      prepositional: "Красноярске",
      phone_display: "8(800)000-00-17",
      phone_href: "88000000017",
      address: "ул. Красноярская, д. 21",
      email: "krasnoyarsk.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    krym: {
      name: "Крым",
      genitive: "Крыма",
      dative: "Крыму",
      accusative: "Крым",
      instrumental: "Крымом",
      prepositional: "Крыму",
      phone_display: "8(800)000-00-18",
      phone_href: "88000000018",
      address: "ул. Крымская, д. 21",
      email: "krym.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    lipeck: {
      name: "Липецк",
      genitive: "Липецка",
      dative: "Липецку",
      accusative: "Липецк",
      instrumental: "Липецком",
      prepositional: "Липецке",
      phone_display: "8(800)000-00-19",
      phone_href: "88000000019",
      address: "ул. Липецкая, д. 21",
      email: "lipeck.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    lugansk: {
      name: "Луганск",
      genitive: "Луганска",
      dative: "Луганску",
      accusative: "Луганск",
      instrumental: "Луганском",
      prepositional: "Луганске",
      phone_display: "8(800)000-00-20",
      phone_href: "88000000020",
      address: "ул. Луганская, д. 21",
      email: "lugansk.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    moscow: {
      name: "Москва",
      genitive: "Москвы",
      dative: "Москве",
      accusative: "Москву",
      instrumental: "Москвой",
      prepositional: "Москве",
      phone_display: "8(800)000-00-21",
      phone_href: "88000000021",
      address: "ул. Московская, д. 21",
      email: "moscow.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    nabchelny: {
      name: "Набережные Челны",
      genitive: "Набережных Челнов",
      dative: "Набережным Челнам",
      accusative: "Набережные Челны",
      instrumental: "Набережными Челнами",
      prepositional: "Набережных Челнах",
      phone_display: "8(800)000-00-22",
      phone_href: "88000000022",
      address: "ул. Набережночелнинская, д. 21",
      email: "nabchelny.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    nnovgorod: {
      name: "Нижний Новгород",
      genitive: "Нижнего Новгорода",
      dative: "Нижнему Новгороду",
      accusative: "Нижний Новгород",
      instrumental: "Нижним Новгородом",
      prepositional: "Нижнем Новгороде",
      phone_display: "8(800)000-00-23",
      phone_href: "88000000023",
      address: "ул. Нижегородская, д. 21",
      email: "nnovgorod.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    novosibirsk: {
      name: "Новосибирск",
      genitive: "Новосибирска",
      dative: "Новосибирску",
      accusative: "Новосибирск",
      instrumental: "Новосибирском",
      prepositional: "Новосибирске",
      phone_display: "8(800)000-00-24",
      phone_href: "88000000024",
      address: "ул. Новосибирская, д. 21",
      email: "novosibirsk.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    omsk: {
      name: "Омск",
      genitive: "Омска",
      dative: "Омску",
      accusative: "Омск",
      instrumental: "Омском",
      prepositional: "Омске",
      phone_display: "8(800)000-00-25",
      phone_href: "88000000025",
      address: "ул. Омская, д. 21",
      email: "omsk.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    orel: {
      name: "Орел",
      genitive: "Орла",
      dative: "Орлу",
      accusative: "Орел",
      instrumental: "Орлом",
      prepositional: "Орле",
      phone_display: "8(800)000-00-26",
      phone_href: "88000000026",
      address: "ул. Орловская, д. 21",
      email: "orel.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    orenburg: {
      name: "Оренбург",
      genitive: "Оренбурга",
      dative: "Оренбургу",
      accusative: "Оренбург",
      instrumental: "Оренбургом",
      prepositional: "Оренбурге",
      phone_display: "8(800)000-00-27",
      phone_href: "88000000027",
      address: "ул. Оренбургская, д. 21",
      email: "orenburg.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    penza: {
      name: "Пенза",
      genitive: "Пензы",
      dative: "Пензе",
      accusative: "Пензу",
      instrumental: "Пензой",
      prepositional: "Пензе",
      phone_display: "8(800)000-00-28",
      phone_href: "88000000028",
      address: "ул. Пензенская, д. 21",
      email: "penza.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    perm: {
      name: "Пермь",
      genitive: "Перми",
      dative: "Перми",
      accusative: "Пермь",
      instrumental: "Пермью",
      prepositional: "Перми",
      phone_display: "8(800)000-00-29",
      phone_href: "88000000029",
      address: "ул. Пермская, д. 21",
      email: "perm.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    rostov: {
      name: "Ростов-на-Дону",
      genitive: "Ростова-на-Дону",
      dative: "Ростову-на-Дону",
      accusative: "Ростов-на-Дону",
      instrumental: "Ростовом-на-Дону",
      prepositional: "Ростове-на-Дону",
      phone_display: "8(800)000-00-30",
      phone_href: "88000000030",
      address: "ул. Ростовская, д. 21",
      email: "rostov.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    ryazan: {
      name: "Рязань",
      genitive: "Рязани",
      dative: "Рязани",
      accusative: "Рязань",
      instrumental: "Рязанью",
      prepositional: "Рязани",
      phone_display: "8(800)000-00-31",
      phone_href: "88000000031",
      address: "ул. Рязанская, д. 21",
      email: "ryazan.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    samara: {
      name: "Самара",
      genitive: "Самары",
      dative: "Самаре",
      accusative: "Самару",
      instrumental: "Самарой",
      prepositional: "Самаре",
      phone_display: "8(800)000-00-32",
      phone_href: "88000000032",
      address: "ул. Самарская, д. 21",
      email: "samara.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    spb: {
      name: "Санкт-Петербург",
      genitive: "Санкт-Петербурга",
      dative: "Санкт-Петербургу",
      accusative: "Санкт-Петербург",
      instrumental: "Санкт-Петербургом",
      prepositional: "Санкт-Петербурге",
      phone_display: "8(800)000-00-33",
      phone_href: "88000000033",
      address: "ул. Петербургская, д. 21",
      email: "spb.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    saransk: {
      name: "Саранск",
      genitive: "Саранска",
      dative: "Саранску",
      accusative: "Саранск",
      instrumental: "Саранском",
      prepositional: "Саранске",
      phone_display: "8(800)000-00-34",
      phone_href: "88000000034",
      address: "ул. Саранская, д. 21",
      email: "saransk.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    saratov: {
      name: "Саратов",
      genitive: "Саратова",
      dative: "Саратову",
      accusative: "Саратов",
      instrumental: "Саратовым",
      prepositional: "Саратове",
      phone_display: "8(800)000-00-35",
      phone_href: "88000000035",
      address: "ул. Саратовская, д. 21",
      email: "saratov.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    smolensk: {
      name: "Смоленск",
      genitive: "Смоленска",
      dative: "Смоленску",
      accusative: "Смоленск",
      instrumental: "Смоленском",
      prepositional: "Смоленске",
      phone_display: "8(800)000-00-36",
      phone_href: "88000000036",
      address: "ул. Смоленская, д. 21",
      email: "smolensk.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    stavropol: {
      name: "Ставрополь",
      genitive: "Ставрополя",
      dative: "Ставрополю",
      accusative: "Ставрополь",
      instrumental: "Ставрополем",
      prepositional: "Ставрополе",
      phone_display: "8(800)000-00-37",
      phone_href: "88000000037",
      address: "ул. Ставропольская, д. 21",
      email: "stavropol.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    tver: {
      name: "Тверь",
      genitive: "Твери",
      dative: "Твери",
      accusative: "Тверь",
      instrumental: "Тверью",
      prepositional: "Твери",
      phone_display: "8(800)000-00-38",
      phone_href: "88000000038",
      address: "ул. Тверская, д. 21",
      email: "tver.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    tolyatti: {
      name: "Тольятти",
      genitive: "Тольятти",
      dative: "Тольятти",
      accusative: "Тольятти",
      instrumental: "Тольятти",
      prepositional: "Тольятти",
      phone_display: "8(800)000-00-39",
      phone_href: "88000000039",
      address: "ул. Тольяттинская, д. 21",
      email: "tolyatti.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    tomsk: {
      name: "Томск",
      genitive: "Томска",
      dative: "Томску",
      accusative: "Томск",
      instrumental: "Томском",
      prepositional: "Томске",
      phone_display: "8(800)000-00-40",
      phone_href: "88000000040",
      address: "ул. Томская, д. 21",
      email: "tomsk.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    tyumen: {
      name: "Тюмень",
      genitive: "Тюмени",
      dative: "Тюмени",
      accusative: "Тюмень",
      instrumental: "Тюменью",
      prepositional: "Тюмени",
      phone_display: "8(800)000-00-41",
      phone_href: "88000000041",
      address: "ул. Тюменская, д. 21",
      email: "tyumen.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    ulyanovsk: {
      name: "Ульяновск",
      genitive: "Ульяновска",
      dative: "Ульяновску",
      accusative: "Ульяновск",
      instrumental: "Ульяновском",
      prepositional: "Ульяновске",
      phone_display: "8(800)000-00-42",
      phone_href: "88000000042",
      address: "ул. Ульяновская, д. 21",
      email: "ulyanovsk.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    ufa: {
      name: "Уфа",
      genitive: "Уфы",
      dative: "Уфе",
      accusative: "Уфу",
      instrumental: "Уфой",
      prepositional: "Уфе",
      phone_display: "8(800)000-00-43",
      phone_href: "88000000043",
      address: "ул. Уфимская, д. 21",
      email: "ufa.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    habarovsk: {
      name: "Хабаровск",
      genitive: "Хабаровска",
      dative: "Хабаровску",
      accusative: "Хабаровск",
      instrumental: "Хабаровском",
      prepositional: "Хабаровске",
      phone_display: "8(800)000-00-44",
      phone_href: "88000000044",
      address: "ул. Хабаровская, д. 21",
      email: "habarovsk.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    cheboksary: {
      name: "Чебоксары",
      genitive: "Чебоксар",
      dative: "Чебоксарам",
      accusative: "Чебоксары",
      instrumental: "Чебоксарами",
      prepositional: "Чебоксарах",
      phone_display: "8(800)000-00-45",
      phone_href: "88000000045",
      address: "ул. Чебоксарская, д. 21",
      email: "cheboksary.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    chelyabinsk: {
      name: "Челябинск",
      genitive: "Челябинска",
      dative: "Челябинску",
      accusative: "Челябинск",
      instrumental: "Челябинском",
      prepositional: "Челябинске",
      phone_display: "8(800)000-00-46",
      phone_href: "88000000046",
      address: "ул. Челябинская, д. 21",
      email: "chelyabinsk.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
    yaroslavl: {
      name: "Ярославль",
      genitive: "Ярославля",
      dative: "Ярославлю",
      accusative: "Ярославль",
      instrumental: "Ярославлем",
      prepositional: "Ярославле",
      phone_display: "8(800)000-00-47",
      phone_href: "88000000047",
      address: "ул. Ярославская, д. 21",
      email: "yaroslavl.metall@mail.ru",
      telegram: "https://t.me/example",
      whatsapp: "https://wa.me/79999999999"
    },
  };
  export default city;
  